### PR TITLE
Add `message_id` Option to `/helper`

### PR DESCRIPTION
**Pull request by Infiniticity**

### CODE REVIEW

**Review by Sachin-dot-py — CHANGES_REQUESTED** [review]
On line 674 please use `url = self.message.jump_url` to make it more concise and reduce chance of bugs.
On line 698 also you can use `str(interaction.user)` instead of `f"{interaction.user.name}#{interaction.user.discriminator}"` for the same reason

**Comment by Infiniticity** [comment]
>>> On line 674 please use `url = self.message.jump_url` to make it more concise and reduce chance of bugs.
This will just link to the message containing the ping and not the provided message.

**Comment by Sachin-dot-py** [comment]
Oh sorry, but you can still use the jump_url property of the right message

**Comment by Infiniticity** [comment]
> Oh sorry, but you can still use the jump_url property of the right message

That is not possible because the command is just collecting the message ID.
In order to do that, the message would have to be fetched.

**Review by Sachin-dot-py — APPROVED** [review]

**Pull request merged**
