### PR TITLE
Edited the embed command

### PR DESCRIPTION
**Pull request by vsmart-06**
The embed command has been edited to use `\n` for a new line rather than `//`

### CODE REVIEW

**Review by Sachin-dot-py — CHANGES_REQUESTED** [review]
Can you change it to \n instead of \\n

**Comment by vsmart-06** [comment]
What does that mean lol

**Comment by Sachin-dot-py** [comment]
In your code we need to use “\\n” to separate lines. Instead can we use “\n” to separate lines?

**Comment by vsmart-06** [comment]
No, while typing the message on discord its \n only but for some reason in the code it has to be changed with \\n

**Pull request merged**
